
CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL,
    user_password TEXT NOT NULL,
    user_email TEXT NOT NULL
);

INSERT INTO public.users (user_name,user_password,user_email) VALUES ('admin','123','admin@gmail.com');

CREATE TABLE exercises (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    name varchar NOT NULL,
    exercise_length INTEGER DEFAULT 0 NOT NULL,
    date TIMESTAMP DEFAULT now() NOT NULL,
    notes varchar NOT NULL
);



-- INSERT INTO public.users_countries (user_id,country_id,nicename,is_visited,is_wish_list) VALUES (1,3,'Algeria',0,1),(1,4,'American Samoa',1,0);

